### ISSUE TITLE
Problems on applying free-sidecar on MacOS catalina 10.15.4  (Last update)

### ISSUE THREAD

**Issue by imyelmo** [ben-z/free-sidecar#59]
Please fill in the template below to speed up the review process:

**Mac model:**: MacBookPro12,1
**iPad model:**: iPad8,1

**Mac version** (optional): 10.15.4
**iPad version** (optional): 13.4

**Comments:**

I have found the following error related with custom/adhoc identity after signing properly SideCore:

Dyld Error Message:
  Library not loaded: /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore
  Referenced from: /System/Library/PrivateFrameworks/MarkupUI.framework/Versions/A/MarkupUI
  Reason: no suitable image found.  Did find:
	/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore: code signature in (/System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore) **not valid for use in process using Library Validation: mapped file has no Team ID and is not a platform binary (signed with custom identity or adhoc?)**

Might it be necessary extra workaround on the signing process to solve this issue?

**Comment by pofixifop** [comment]
i had same issue. Did you try signing with XCode 11.4? I reverted back and didn't try, but realized later that XCode updated as well.

**Comment by imyelmo** [comment]
Yeah, I tried after update Xcode to last version,  just after updating the O.S. :I

**Comment by sam-thornton** [comment]
My sidecar also stopped working after the OS update. I tried repeating the process and it completely broke Finder, couldn’t run any applications including Terminal.

Not sure if this is the same issue, but posting here as it’s relevant to Catalina 10.15.4 (running on Macbook Air 7,2). Currently attempting to reinstall Catalina through recovery mode.

**Comment by ben-z** [comment]
You are right. Apple seems to have done something fishy in the last update that broke self-signed SidecarCore files. It appears that we need a signature with a valid Team ID.

This is moving beyond my knowledge on Apple's code signing process... Any help is appreciated. I will update the README to reflect this issue.

Also for anyone having weird issues after applying `SidecarCore`. There's no need to do complete re-installs. Just copy back the backup file and reboot:

```
sudo cp ~/Downloads/SidecarCore.bak /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore
```

**Comment by imyelmo** [comment]
> You are right. Apple seems to have done something fishy in the last update that breaks self-signed SidecarCore files. It appears that we need a signature with valid Team ID.
> 
> This is moving beyond my knowledge on Apple's code signing process... Any help is appreciated. I will update the README to reflect this issue.
> 
> Also for anyone having weird issues after applying `SidecarCore`. There's no need to do complete re-installs. Just copy back the backup file and reboot:
> 
> ```
> sudo cp ~/Downloads/SidecarCore.bak /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore
> ```

I would say that you are right in everything. Let see if we discover how Team ID works for code signing

**Comment by ben-z** [comment]
Good to see that other communities are discussing the same changes: 
https://forums.macrumors.com/threads/macos-10-15-catalina-on-unsupported-macs.2183772/page-330?post=28198591#post-28198591

I'll take a look at & try out some of the proposed solutions in that forum in the next few days. If anyone's adventurous please take a look as well :).

~It appears that we may need to venture into the realm of non-stock boot loaders so we can pass in flags :fearful:.~
Update: (We don't! It's the NVRAM boot flags so it's built in: https://github.com/ben-z/free-sidecar/issues/59#issuecomment-603953953)

Some useful things to look at (from the [forum]):
* https://github.com/mologie/macos-disable-library-validation
* the `amfi_get_out_of_my_way` boot flag

[forum]: https://forums.macrumors.com/threads/macos-10-15-catalina-on-unsupported-macs.2183772/page-330?post=28198591#post-28198591

**Comment by ymartin101** [comment]
This issue seems to have broken a lot of things on my Mac. Can't access Chrome, Apple Music, certain settings, etc. It all started after re-enabling System Integrity Protection.

Edit: Troubleshooting tip 7 helped me out here.

**Comment by sam-thornton** [comment]
> This issue seems to have broken a lot of things on my Mac. Can't access Chrome, Apple Music, certain settings, etc. It all started after re-enabling System Integrity Protection. Any way to revert the changes? :(

I had the same problem exactly, strangely most things were fixed when I turned System Integrity Protection back off. 

Obviously this is not a good long term fix, so I booted back into recovery mode and reinstalled the OS. All of my files, settings, and applications were intact afterward.

**Comment by ymartin101** [comment]
> > This issue seems to have broken a lot of things on my Mac. Can't access Chrome, Apple Music, certain settings, etc. It all started after re-enabling System Integrity Protection. Any way to revert the changes? :(
> 
> I had the same problem exactly, strangely most things were fixed when I turned System Integrity Protection back off.
> 
> Obviously this is not a good long term fix, so I booted back into recovery mode and reinstalled the OS. All of my files, settings, and applications were intact afterward.

I reverted to the .bak core file - everything seems to be fine again now after rebooting. Strange thing is that I actually got an error when attempting to sign the SidecarCore, but it still seems to have worked.

Anyway, is there definitely no way to get Sidecar running on 10.15.4 using this workaround right now? :(

**Comment by herbit** [comment]
I also reverted to the .bak file, without signing again and everything is back to normal.

**Comment by ben-z** [comment]
Ya just reverting the backup file should fix the system. No need to do a whole reinstall lol. It’s called backup for a reason:

https://github.com/ben-z/free-sidecar/issues/59#issuecomment-603693357

I should update the readme to remove the signing step because the backup file is already signed. (Done).

**Comment by ben-z** [comment]
LOL just realized there's a really simple workaround. It makes the machine less secure though.

Steps adapted from [this comment](https://forums.macrumors.com/threads/macos-10-15-catalina-on-unsupported-macs.2183772/page-330?post=28198591#post-28198591):

1. Follow all the steps in README to obtain a patched `SidecarCore`, place it in the system directory and sign it.
2. Before restarting, add `amfi_get_out_of_my_way=0x1` to your NVRAM boot flags. i.e. run `sudo nvram boot-args="amfi_get_out_of_my_way=0x1"`. You should not see any error messages.
3. Do not enable SIP.

Then it should work like before. The only downside is that we are disabling AMFI security checks and keeping SIP disabled.

(I'm not going to pretend I'm familiar with AMFI. You can read more about it [here](https://eclecticlight.co/2018/12/29/amfi-checking-file-integrity-on-your-mac/))

A summary:
* Patching `SidecarCore` and self-signing (step 8) it no longer works in 10.15.4.
* A workaround is to do an additional step that's stated in this comment: add a flag to NVRAM boot-args.
* This workaround disables AMFI and requires you to keep SIP disabled. This will loosen the security on your Mac.
* If you enable SIP after patching `SidecarCore` and setting the boot args in 10.15.4, you'll see the same behaviour that others are seeing above: apps crashing with `Termination Reason:    DYLD, [0x5] Code Signature`. Either disable SIP or restore your `SidecarCore.bak`.
* I'll update the README later to reflect this additional step later.

EDIT: some people asked about how to remove the boot flag. [Here is how](https://github.com/ben-z/free-sidecar/issues/72#issuecomment-608559104). In general, if you type `<some command> --help` you'll be able to see what options the command offers. For example:

```
> nvram --help
nvram: (usage: no such option as --)
nvram [-x] [-p] [-f filename] [-d name] [-c] name[=value] ...
	-x         use XML format for printing or reading variables
	           (must appear before -p or -f)
	-p         print all firmware variables
	-f         set firmware variables from a text file
	-d         delete the named variable
	-c         delete all variables
	name=value set named variable
	name       print variable
Note that arguments and options are executed in order.
```

As we can see, `-d` deletes a variable.

**Comment by sduarteurbina** [comment]
Ah, you beat me by a few minutes :P 

I just did the same and can confirm that it stops the issue with app crashing due to the new AMFI enforcements. However, it seems as if my iPad 5 on iOS 13.4 no longer connects as reliably with my compatible late 2015 iMac. It only establishes (over wire) a connection 4/5 times, and the times that it does work, the iPad maintains a connection with the Mac for only 20 seconds or so, and then the connection drops and tries to connect wirelessly (which has never worked for me).

Does anyone else have this issue?

**Comment by imyelmo** [comment]
Hi,

I don’t fully remember my tests yesterday, but I think that it is enough if you disable SIP. The other thing that you mention, does it apply if you enable SIP?. In that way, it would say that  it is  a more secure workaround than simply disabling SIP, I guess.

**Comment by ben-z** [comment]
@imyelmo It wasn't enough for me to just disable SIP. The main problem I had was that most of the system status bar icons weren't showing up (Notification Center, spotlight, etc.). Adding the `amfi_get_out_of_my_way` flag (and keeping SIP disabled) did solve the problem.

@techguy9 Glad you are looking at the same solution :). Did you try turning off wifi and bluetooth on your iPad? That would force it to use the wired connection at all times. I haven't been seeing the same issue on my end with iPad Air 2 and MBP '19.

**Comment by ben-z** [comment]
Updated the README. This should be fixed now. I will close this issue.

**Comment by herbit** [comment]
In SidecarPatcher it should fixed, with SIP still enabled? See https://github.com/pookjw/SidecarPatcher/issues/48

**Comment by ben-z** [comment]
In my experience SIP must be kept disabled. Otherwise the system acts like the boot flag isn’t there (apps crash, status bar icons disappear, etc.) @pookjw do you observe the same?

**Comment by olmedocr** [comment]
Restoring the backup does not fix anything, even if i keep SIP disabled and the NVRAM flag as stated above

**Comment by RumplesWrinkles** [comment]
Thanks for the help on this everyone! If I'm wanting to revert the changes I made, what command line should I use to revert the NVRAM setting used above?

sudo nvram boot-args="amfi_get_out_of_my_way=0x1"

**Comment by talaviram** [comment]
I wonder if this could help for 10.15.4 (though it WILL break I guess on future builds...)
https://siguza.github.io/psychicpaper/

**Comment by jafarvillan** [comment]
> My sidecar also stopped working after the OS update. I tried repeating the process and it completely broke Finder, couldn’t run any applications including Terminal.
> 
> Not sure if this is the same issue, but posting here as it’s relevant to Catalina 10.15.4 (running on Macbook Air 7,2). Currently attempting to reinstall Catalina through recovery mode.

Hi 
I am facing same issue, did you try reinstalling the iOS ?

**Comment by jafarvillan** [comment]
> You are right. Apple seems to have done something fishy in the last update that broke self-signed SidecarCore files. It appears that we need a signature with a valid Team ID.
> 
> This is moving beyond my knowledge on Apple's code signing process... Any help is appreciated. I will update the README to reflect this issue.
> 
> Also for anyone having weird issues after applying `SidecarCore`. There's no need to do complete re-installs. Just copy back the backup file and reboot:
> 
> ```
> sudo cp ~/Downloads/SidecarCore.bak /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore
> ```

I tried to run the command, but it says there’s no file or directory though  I have the backup file In downloads folder, for some my finder is also crashed :(

**Comment by bladewangpro** [comment]
> > You are right. Apple seems to have done something fishy in the last update that broke self-signed SidecarCore files. It appears that we need a signature with a valid Team ID.
> > This is moving beyond my knowledge on Apple's code signing process... Any help is appreciated. I will update the README to reflect this issue.
> > Also for anyone having weird issues after applying `SidecarCore`. There's no need to do complete re-installs. Just copy back the backup file and reboot:
> > ```
> > sudo cp ~/Downloads/SidecarCore.bak /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore
> > ```
> 
> I tried to run the command, but it says there’s no file or directory though I have the backup file In downloads folder, for some my finder is also crashed :(

You need to mount system volume as read-write at first then copy back the backup file..

sudo mount -uw /
sudo cp ~/Downloads/SidecarCore.bak /System/Library/PrivateFrameworks/SidecarCore.framework/Versions/A/SidecarCore

**Comment by paubarrina** [comment]
> LOL just realized there's a really simple workaround. It makes the machine less secure though.
> 
> Steps adapted from [this comment](https://forums.macrumors.com/threads/macos-10-15-catalina-on-unsupported-macs.2183772/page-330?post=28198591#post-28198591):
> 
>     1. Follow all the steps in README to obtain a patched `SidecarCore`, place it in the system directory and sign it.
> 
>     2. Before restarting, add `amfi_get_out_of_my_way=0x1` to your NVRAM boot flags. i.e. run `sudo nvram boot-args="amfi_get_out_of_my_way=0x1"`. You should not see any error messages.
> 
>     3. Do not enable SIP.
> 
> 
> Then it should work like before. The only downside is that we are disabling AMFI security checks and keeping SIP disabled.
> 
> (I'm not going to pretend I'm familiar with AMFI. You can read more about it [here](https://eclecticlight.co/2018/12/29/amfi-checking-file-integrity-on-your-mac/))
> 
> A summary:
> 
>     * Patching `SidecarCore` and self-signing (step 8) it no longer works in 10.15.4.
> 
>     * A workaround is to do an additional step that's stated in this comment: add a flag to NVRAM boot-args.
> 
>     * This workaround disables AMFI and requires you to keep SIP disabled. This will loosen the security on your Mac.
> 
>     * If you enable SIP after patching `SidecarCore` and setting the boot args in 10.15.4, you'll see the same behaviour that others are seeing above: apps crashing with `Termination Reason:    DYLD, [0x5] Code Signature`. Either disable SIP or restore your `SidecarCore.bak`.
> 
>     * I'll update the README later to reflect this additional step later.
> 
> 
> EDIT: some people asked about how to remove the boot flag. [Here is how](https://github.com/ben-z/free-sidecar/issues/72#issuecomment-608559104). In general, if you type `<some command> --help` you'll be able to see what options the command offers. For example:
> 
> ```
> > nvram --help
> nvram: (usage: no such option as --)
> nvram [-x] [-p] [-f filename] [-d name] [-c] name[=value] ...
> 	-x         use XML format for printing or reading variables
> 	           (must appear before -p or -f)
> 	-p         print all firmware variables
> 	-f         set firmware variables from a text file
> 	-d         delete the named variable
> 	-c         delete all variables
> 	name=value set named variable
> 	name       print variable
> Note that arguments and options are executed in order.
> ```
> 
> As we can see, `-d` deletes a variable.

And how can I enable AMFI security check again?

**Comment by ben-z** [comment]
It's in the last section of your quoted text:

`sudo nvram -d boot-args`

**Comment by fliptheweb** [comment]
Guys, be careful with disabled SIP (besides security reasons) – on Catalina after disabling you couldn't grant the application permission to Camera and Microphone (eg for Skype/Slack)

Details:
https://apple.stackexchange.com/a/384311

**Comment by eexit** [comment]
> Guys, be careful with disabled SIP (besides security reasons) – on Catalina after disabling you couldn't grant the application permission to Camera and Microphone (eg for Skype/Slack)

Agreed. I tried to launch Zoom a first time and the video access couldn't be granted, I had to disable the NVRAM flag, reboot, re-open Zoom, then re-enable the NVRAM flag (+reboot).

If anyone has some expertise to share around this to avoid such cumbersome process, it would be greatly appreciated.

Thanks!

Edit: this is too much trouble, I'm reverting Sidecar until there is another way to re-enable SIP.
